displayName: Gateway Authentication
type: middleware

import: github.com/rootservices/auth

summary: A Gateway Authentication middleware for Traefik.
testData:
  HeaderName: Test-Header
  Provider: google
  Audience: required-audience